apiVersion: v1
kind: ReplicationController
metadata:
  name: phpmyadmin
  labels:
    heritage: helm 
spec:
  replicas: 1
  selector:
    app: phpmyadmin
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadmin
    spec:
      containers: 
      - name: phpmyadmin
        image: hub.wiseweb.co:5000/contentoff/phpmyadmin:latest
        imagePullPolicy: Always
        ports: 
          - containerPort: 80
            name: phpmyadmin
