apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: phpmyadmin
  name: phpmyadmin
spec:
  type: NodePort 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30009
  selector: 
    app: phpmyadmin
  
