apiVersion: v1
kind: ReplicationController
metadata:
  name: sonar
  labels:
    name: sonar
spec:
  replicas: 1
  selector:
    name: sonar
    role: code-check
  template:
    metadata:
      name: sonar
      labels:
        name: sonar
        role: code-check
    spec:
      volumes:
      - name: sonardata
        nfs:
          server: 172.30.17.5
          path: "/srv/nfs/kube/sq/data"
          readOnly: false
        # iscsi:
        #   targetPortal: 172.30.17.5:3260
        #   iqn: iqn.2016-08.co.wiseweb.kube:san1.sdb2
        #   lun: 1
        #   fsType: ext4
        #   readOnly: false
      - name: sonarextensions
        nfs:
          server: 172.30.17.5
          path: "/srv/nfs/kube/sq/extensions"
          readOnly: false
      containers:
      - name: sonar
        image: zensam/sonar
        imagePullPolicy: Always
        ports:
        - name: sqport
          containerPort: 9000
        - name: pgport
          containerPort: 5432
        volumeMounts:
          - name: sonardata
            mountPath: "/opt/sonarqube/data"
          - name: sonarextensions
            mountPath: "/opt/sonarqube/extensions"
