apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
    heritage: helm
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: jnlp
    port: 50000
  selector:
    app: jenkins
